#!/bin/bash

pkg_flag=$1
pkg_name=${@: -1}

if [[ ${pkg_flag} = "--version" ]]; then
  echo "faked ffmpeg pkg-config for android v1.0"
  exit 0
fi

# output faked pkg-config information for libass and related libs
if [[ "${pkg_name}" = "libass"
  || "${pkg_name}" = "fontconfig"
  || "${pkg_name}" = "freetype"
  || "${pkg_name}" = "fribidi"
  || "${pkg_name}" = "expat" ]]; then
  case ${pkg_flag} in
    --cflags)
      echo "-I${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/expat/include \
        -I${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/fontconfig/include \
        -I${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/freetype/include \
        -I${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/fribidi/include \
        -I${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/libass/include"
      exit 0
      ;;
   --libs)
      echo "-L${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/expat/lib -lexpat\
        -L${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/fontconfig/lib -lfontconfig\
        -L${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/freetype/lib -lfreetype\
        -L${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/fribidi/lib -lfribidi\
        -L${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/libass/lib -lass"
      exit 0
      ;;
  *)
      exit 0
      ;;
  esac
fi

# output faked pkg-config information for libopencore_amrnb/libopencore_amrwb
if [[ "${pkg_name}" = "libopencore_amrnb"
  || "${pkg_name}" = "libopencore_amrwb" ]]; then
  case ${pkg_flag} in
    --cflags)
      echo "-I${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/opencore-amr/include"
      exit 0
      ;;
   --libs)
      echo "-L${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/opencore-amr/lib -lopencore-amrnb -lopencore-amrwb"
      exit 0
      ;;
  *)
      exit 0
      ;;
  esac
fi

# output faked pkg-config information for libopencore_amrnb/libopencore_amrwb
if [[ "${pkg_name}" = "libx264" ]]; then
  case ${pkg_flag} in
    --cflags)
      echo "-I${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/libx264/include"
      exit 0
      ;;
   --libs)
      echo "-L${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/libx264/lib -lx264"
      exit 0
      ;;
  *)
      exit 0
      ;;
  esac
fi

# output faked pkg-config information for libfdk-aac
if [[ "${pkg_name}" = "libfdk-aac" ]]; then
  case ${pkg_flag} in
    --cflags)
      echo "-I${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/libfdk-aac/include"
      exit 0
      ;;
   --libs)
      echo "-L${BASE_DIR}/../ffmpeg-external-libs/${LIB_BASE_DIR}/libfdk-aac/lib -lfdk-aac"
      exit 0
      ;;
  *)
      exit 0
      ;;
  esac
fi

# output faked pkg-config information for ... (add new lib information here)

exit 1
