	.arch armv5te
	.fpu softvfp
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 6
	.eabi_attribute 34, 0
	.eabi_attribute 18, 4
	.file	"aecm_core_neon_offsets.c"
	.global	offset_aecm_dfaCleanQDomain
	.data
	.align	2
	.type	offset_aecm_dfaCleanQDomain, %object
	.size	offset_aecm_dfaCleanQDomain, 4
offset_aecm_dfaCleanQDomain:
	.word	13980
	.global	offset_aecm_outBuf
	.align	2
	.type	offset_aecm_outBuf, %object
	.size	offset_aecm_outBuf, 4
offset_aecm_outBuf:
	.word	15992
	.global	offset_aecm_xBuf
	.align	2
	.type	offset_aecm_xBuf, %object
	.size	offset_aecm_xBuf, 4
offset_aecm_xBuf:
	.word	15980
	.global	offset_aecm_dBufNoisy
	.align	2
	.type	offset_aecm_dBufNoisy, %object
	.size	offset_aecm_dBufNoisy, 4
offset_aecm_dBufNoisy:
	.word	15988
	.global	offset_aecm_dBufClean
	.align	2
	.type	offset_aecm_dBufClean, %object
	.size	offset_aecm_dBufClean, 4
offset_aecm_dBufClean:
	.word	15984
	.global	offset_aecm_channelStored
	.align	2
	.type	offset_aecm_channelStored, %object
	.size	offset_aecm_channelStored, 4
offset_aecm_channelStored:
	.word	15968
	.global	offset_aecm_channelAdapt16
	.align	2
	.type	offset_aecm_channelAdapt16, %object
	.size	offset_aecm_channelAdapt16, 4
offset_aecm_channelAdapt16:
	.word	15972
	.global	offset_aecm_channelAdapt32
	.align	2
	.type	offset_aecm_channelAdapt32, %object
	.size	offset_aecm_channelAdapt32, 4
offset_aecm_channelAdapt32:
	.word	15976
	.global	offset_aecm_real_fft
	.align	2
	.type	offset_aecm_real_fft, %object
	.size	offset_aecm_real_fft, 4
offset_aecm_real_fft:
	.word	17220
	.ident	"GCC: (GNU) 4.9 20140827 (prerelease)"
	.section	.note.GNU-stack,"",%progbits
