	.arch armv5te
	.fpu softvfp
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 6
	.eabi_attribute 34, 0
	.eabi_attribute 18, 4
	.file	"nsx_core_neon_offsets.c"
	.global	offset_nsx_anaLen
	.data
	.align	2
	.type	offset_nsx_anaLen, %object
	.size	offset_nsx_anaLen, 4
offset_nsx_anaLen:
	.word	3112
	.global	offset_nsx_anaLen2
	.align	2
	.type	offset_nsx_anaLen2, %object
	.size	offset_nsx_anaLen2, 4
offset_nsx_anaLen2:
	.word	3116
	.global	offset_nsx_normData
	.align	2
	.type	offset_nsx_normData, %object
	.size	offset_nsx_normData, 4
offset_nsx_normData:
	.word	13120
	.global	offset_nsx_analysisBuffer
	.align	2
	.type	offset_nsx_analysisBuffer, %object
	.size	offset_nsx_analysisBuffer, 4
offset_nsx_analysisBuffer:
	.word	8
	.global	offset_nsx_synthesisBuffer
	.align	2
	.type	offset_nsx_synthesisBuffer, %object
	.size	offset_nsx_synthesisBuffer, 4
offset_nsx_synthesisBuffer:
	.word	520
	.global	offset_nsx_blockLen10ms
	.align	2
	.type	offset_nsx_blockLen10ms, %object
	.size	offset_nsx_blockLen10ms, 4
offset_nsx_blockLen10ms:
	.word	12084
	.global	offset_nsx_window
	.align	2
	.type	offset_nsx_window, %object
	.size	offset_nsx_window, 4
offset_nsx_window:
	.word	4
	.global	offset_nsx_real
	.align	2
	.type	offset_nsx_real, %object
	.size	offset_nsx_real, 4
offset_nsx_real:
	.word	12088
	.global	offset_nsx_imag
	.align	2
	.type	offset_nsx_imag, %object
	.size	offset_nsx_imag, 4
offset_nsx_imag:
	.word	12600
	.global	offset_nsx_noiseSupFilter
	.align	2
	.type	offset_nsx_noiseSupFilter, %object
	.size	offset_nsx_noiseSupFilter, 4
offset_nsx_noiseSupFilter:
	.word	1032
	.global	offset_nsx_magnLen
	.align	2
	.type	offset_nsx_magnLen, %object
	.size	offset_nsx_magnLen, 4
offset_nsx_magnLen:
	.word	3120
	.global	offset_nsx_noiseEstLogQuantile
	.align	2
	.type	offset_nsx_noiseEstLogQuantile, %object
	.size	offset_nsx_noiseEstLogQuantile, 4
offset_nsx_noiseEstLogQuantile:
	.word	1300
	.global	offset_nsx_noiseEstQuantile
	.align	2
	.type	offset_nsx_noiseEstQuantile, %object
	.size	offset_nsx_noiseEstQuantile, 4
offset_nsx_noiseEstQuantile:
	.word	2854
	.global	offset_nsx_qNoise
	.align	2
	.type	offset_nsx_qNoise, %object
	.size	offset_nsx_qNoise, 4
offset_nsx_qNoise:
	.word	12072
	.global	offset_nsx_stages
	.align	2
	.type	offset_nsx_stages, %object
	.size	offset_nsx_stages, 4
offset_nsx_stages:
	.word	3128
	.global	offset_nsx_blockIndex
	.align	2
	.type	offset_nsx_blockIndex, %object
	.size	offset_nsx_blockIndex, 4
offset_nsx_blockIndex:
	.word	5548
	.global	offset_nsx_noiseEstCounter
	.align	2
	.type	offset_nsx_noiseEstCounter, %object
	.size	offset_nsx_noiseEstCounter, 4
offset_nsx_noiseEstCounter:
	.word	2848
	.global	offset_nsx_noiseEstDensity
	.align	2
	.type	offset_nsx_noiseEstDensity, %object
	.size	offset_nsx_noiseEstDensity, 4
offset_nsx_noiseEstDensity:
	.word	2074
	.ident	"GCC: (GNU) 4.9 20140827 (prerelease)"
	.section	.note.GNU-stack,"",%progbits
