/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_com_example_library_NativeEngine */

#ifndef _Included_main_java_com_example_library_NativeEngine
#define _Included_main_java_com_example_library_NativeEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setModel
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setSysName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setSysName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setSysVersion
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setSysVersion
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setVersionName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setVersionName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setDeviceURN
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setDeviceURN
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setDeviceIMEI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setDeviceIMEI
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setCPUChip
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setCPUChip
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setCPUArch
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setCPUArch
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setBrand
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setBrand
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setUUID
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setUUID
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setPackageName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setPackageName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setDocumentPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setDocumentPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    getSoVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_java_com_example_library_NativeEngine_getSoVersion
  (JNIEnv *, jclass);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    initWithAppkey
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_initWithAppkey
  (JNIEnv *, jclass, jstring, jstring, jint, jstring);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    inputVideoFrame
 * Signature: ([BIIIIIIJ)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_inputVideoFrame
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jint, jint, jlong);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    inputAudioFrame
 * Signature: ([BIJIZ)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_inputAudioFrame
  (JNIEnv *, jclass, jbyteArray, jint, jlong, jint, jboolean);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    startCapture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_java_com_example_library_NativeEngine_startCapture
  (JNIEnv *, jclass);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    stopCapture
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_stopCapture
  (JNIEnv *, jclass);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    switchCamera
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_main_java_com_example_library_NativeEngine_switchCamera
  (JNIEnv *, jclass);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    onNetWorkChanged
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_onNetWorkChanged
  (JNIEnv *, jclass, jint);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    AudioRecorderBufRefresh
 * Signature: (Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_AudioRecorderBufRefresh
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    AudioPlayerBufRefresh
 * Signature: (Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_AudioPlayerBufRefresh
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setServerMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setServerMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     main_java_com_example_library_NativeEngine
 * Method:    setServerIpPort
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_main_java_com_example_library_NativeEngine_setServerIpPort
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
