/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_youme_mixers_VideoMixerNative */

#ifndef _Included_com_youme_mixers_VideoMixerNative
#define _Included_com_youme_mixers_VideoMixerNative
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_youme_mixers_VideoMixerNative
     * Method:    videoFrameMixerCallback
     * Signature: (II[FIIJ)V
     */
    JNIEXPORT void JNICALL Java_com_youme_mixers_VideoMixerNative_videoFrameMixerCallback
    (JNIEnv *, jclass, jint, jint, jfloatArray, jint, jint, jlong);
    
    /*
     * Class:     com_youme_mixers_VideoMixerNative
     * Method:    videoNetFirstCallback
     * Signature: (II[FIIJ)V
     */
    JNIEXPORT void JNICALL Java_com_youme_mixers_VideoMixerNative_videoNetFirstCallback
    (JNIEnv *, jclass, jint, jint, jfloatArray, jint, jint, jlong);
    
    /*
     * Class:     com_youme_mixers_VideoMixerNative
     * Method:    videoNetSecondCallback
     * Signature: (II[FIIJ)V
     */
    JNIEXPORT void JNICALL Java_com_youme_mixers_VideoMixerNative_videoNetSecondCallback
    (JNIEnv *, jclass, jint, jint, jfloatArray, jint, jint, jlong);
    
    /*
     * Class:     com_youme_mixers_VideoMixerNative
     * Method:    videoFrameMixerDataCallback
     * Signature: (I[BIIJ)V
     */
    JNIEXPORT void JNICALL Java_com_youme_mixers_VideoMixerNative_videoFrameMixerDataCallback
    (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jlong);
    
    /*
     * Class:     com_youme_mixers_VideoMixerNative
     * Method:    videoNetDataFirstCallback
     * Signature: (I[BIIJ)V
     */
    JNIEXPORT void JNICALL Java_com_youme_mixers_VideoMixerNative_videoNetDataFirstCallback
    (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jlong);
    
    /*
     * Class:     com_youme_mixers_VideoMixerNative
     * Method:    videoNetDataSecondCallback
     * Signature: (I[BIIJ)V
     */
    JNIEXPORT void JNICALL Java_com_youme_mixers_VideoMixerNative_videoNetDataSecondCallback
    (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jlong);
    
    /*
     * Class:     com_youme_mixers_VideoMixerNative
     * Method:    videoRenderFilterCallback
     * Signature: (IIIII)I
     */
    JNIEXPORT jint JNICALL Java_com_youme_mixers_VideoMixerNative_videoRenderFilterCallback
    (JNIEnv *, jclass, jint, jint, jint, jint, jint);
    
    /*
     * Class:     com_youme_mixers_VideoMixerNative
     * Method:    videoMixerUseTextureOES
     * Signature: (Z)V
     */
    JNIEXPORT void JNICALL Java_com_youme_mixers_VideoMixerNative_videoMixerUseTextureOES
    (JNIEnv *, jclass, jboolean);
    
    /*
     * Class:     com_youme_mixers_VideoMixerNative
     * Method:    isSupportGL3
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_com_youme_mixers_VideoMixerNative_isSupportGL3
    (JNIEnv *, jclass);
    
    /*
     * Class:     com_youme_mixers_VideoMixerNative
     * Method:    glReadPixels
     * Signature: (IIIIII[B)V
     */
    JNIEXPORT void JNICALL Java_com_youme_mixers_VideoMixerNative_glReadPixels
    (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jbyteArray);
    
    /*
     * Class:     com_youme_mixers_VideoMixerNative
     * Method:    glMapBufferRange
     * Signature: (IIIIIII[B)I
     */
    JNIEXPORT jint JNICALL Java_com_youme_mixers_VideoMixerNative_glMapBufferRange
    (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jbyteArray);
    
#ifdef __cplusplus
}
#endif
#endif

